### ISSUE TITLE
ValueError: Can't determine a unique package given abbreviation mmdet

### ISSUE THREAD

**Issue by fangxu622** [open-mmlab/mim-example#4]
```
root@060a3ecd3832:/workspace/mim-example/swin_transformer# CUDA_VISIBLE_DEVICES=0,1,2,3 PORT=27519 PYTHONPATH='/opt/conda/bin/python':$PYTHONPATH mim train mmdet configs/swin_mask_rcnn/swin_L_F1.py --gpus 4 --gpus-per-node 4
Traceback (most recent call last):
  File "/opt/conda/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mim/commands/train.py", line 96, in cli
    is_success, msg = train(
  File "/opt/conda/lib/python3.8/site-packages/mim/commands/train.py", line 156, in train
    raise ValueError(highlighted_error(msg))
ValueError: Can't determine a unique package given abbreviation mmdet
````

I have install mmdet =2.13 mmcv mim

**Comment by kennymckormick** [comment]
This is a bug of MIM, we have resolved in this [PR](https://github.com/open-mmlab/mim/pull/44). Now you can use the master branch of MIM and there will be no bugs.

**Comment by fangxu622** [comment]
Yeah, thanks, but 
why mim can't find the correct path of mmdetection.
on my environment, mmdetection is installed from source. 
and this error 

```
root@060a3ecd3832:/workspace/mim-example/swin_transformer# PYTHONPATH='./':$PYTHONPATH mim train mmdet configs/swin_mask_rcnn/swin_L_F1.py --gpus 4 --gpus-per-node 4
Training command is python /workspace/mmdetection/mmdet/tools/train.py configs/swin_mask_rcnn/swin_L_F1.py --gpus 4 --launcher none.
python: can't open file '/workspace/mmdetection/mmdet/tools/train.py': [Errno 2] No such file or directory
```

the correct path should be '/workspace/mmdetection/mmdet/tools/train.py' and no mmdet string

**Comment by fangxu622** [comment]
@kennymckormick
